CREATE TABLE TASK (
    IDTASK NUMERIC(18) NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATIONDATE DATE NOT NULL,
    ENDDATE DATE
);

ALTER TABLE TASK
    ADD CONSTRAINT XPKTASK
    PRIMARY KEY (IDTASK);

